# Generated by Django 3.2.6 on 2023-09-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tipoDocumentoPaciente', models.CharField(max_length=50)),
                ('numeroPaciente', models.PositiveIntegerField()),
                ('fechaExpedicionDocumentoPaciente', models.DateField()),
                ('lugarExpedicionDocumentoPaciente', models.CharField(max_length=100)),
                ('fechaNacimientoPaciente', models.DateField()),
                ('lugarNacimientoPaciente', models.CharField(max_length=100)),
                ('edadPaciente', models.PositiveIntegerField()),
                ('tipoEdadPaciente', models.CharField(max_length=50)),
                ('primerNombrePaciente', models.CharField(max_length=50)),
                ('segundoNombrePaciente', models.CharField(max_length=50)),
                ('primerApellidoPaciente', models.CharField(max_length=50)),
                ('segundoApellidoPaciente', models.CharField(max_length=50)),
                ('seudonimoPaciente', models.CharField(max_length=50)),
                ('estadoCivilPaciente', models.CharField(max_length=50)),
                ('sexoPaciente', models.CharField(max_length=10)),
                ('grupoSanguineoPaciente', models.CharField(max_length=5)),
                ('celularPaciente', models.PositiveIntegerField()),
                ('whatsappPaciente', models.PositiveIntegerField()),
                ('celularAdicionalPaciente', models.PositiveIntegerField()),
                ('telefonoFijoPaciente', models.PositiveIntegerField()),
                ('correoElectronicoPaciente', models.EmailField(max_length=254)),
                ('lugarResidenciaPaciente', models.CharField(max_length=100)),
                ('localidadPaciente', models.CharField(max_length=50)),
                ('areaUbicacionPaciente', models.CharField(max_length=50)),
                ('paisPaciente', models.CharField(max_length=50)),
                ('departamentoPaciente', models.CharField(max_length=50)),
                ('ciudadPaciente', models.CharField(max_length=50)),
                ('nivelEducativoPaciente', models.CharField(max_length=50)),
                ('ocupacionPaciente', models.CharField(max_length=50)),
                ('tipoVinculacionPaciente', models.CharField(max_length=50)),
                ('codigoPertenenciaEtinicaPaciente', models.CharField(max_length=50)),
                ('poblacionClavePaciente', models.CharField(max_length=50)),
                ('tipoAtencionPaciente', models.CharField(max_length=50)),
                ('epsPaciente', models.CharField(max_length=50)),
                ('tipoAfilicacionPaciente', models.CharField(max_length=50)),
                ('ipsPrimariaPaciente', models.CharField(max_length=50)),
                ('contratoObjetoPaciente', models.CharField(max_length=50)),
                ('estadoPaciente', models.CharField(max_length=100)),
            ],
        ),
    ]
