# Generated by Django 3.2.6 on 2023-09-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Paciente.paciente')),
                ('documentoProfesionalConsulta', models.PositiveIntegerField()),
                ('nombreProfesionalConsulta', models.CharField(max_length=100)),
                ('fechaHoraAtencionConsulta', models.DateTimeField()),
                ('servicioConsulta', models.CharField(max_length=100)),
                ('motivoConsulta', models.TextField()),
                ('enfermedadPaciente', models.TextField()),
                ('diagnosticoPaciente', models.TextField()),
                ('antecedentesPersonalesPaciente', models.TextField()),
                ('antecedentesFamiliaresPaciente', models.TextField()),
                ('antecedentesFarmacologicosPaciente', models.TextField()),
                ('alergiasPaciente', models.TextField()),
                ('vacunasPaciente', models.TextField()),
                ('examenFisicoPaciente', models.TextField()),
                ('signosVitalesPaciente', models.TextField()),
                ('ordenesMedicasPaciente', models.TextField()),
                ('incapacidadMedicaPaciente', models.TextField()),
                ('notaSeguimientoPaciente', models.TextField()),
                ('motivoAtencionFallidaPaciente', models.TextField()),
                ('condicionEgresoPaciente', models.CharField(max_length=100)),
            ],
        ),
    ]
